// Code generated by github.com/negasus/goval. DO NOT EDIT.
// Used flags: -t RequestCustomEmbedItem -t RequestCustomEmbed -t RequestCustom -o goval_request_custom.go

package tests

import (
	"github.com/negasus/goval"
)

func (model *RequestCustomEmbedItem) Validate() goval.Errors {
	errors := goval.Errors{}

	{ // ID
		if model.ID < 10 {
			errors["id"] = append(errors["id"], goval.Error{
				Type: goval.ErrorTypeMinNumeric,
				Values: map[string]any{
					"field":      "id",
					"rule_value": 10,
				},
			})
		}
	}

	return errors
}

func (model *RequestCustomEmbed) Validate() goval.Errors {
	errors := goval.Errors{}

	{ // RequestCustomEmbedItem
		for k, v := range model.RequestCustomEmbedItem.Validate() {
			errors[k] = append(errors[k], v...)
		}
	}

	return errors
}

func (model *RequestCustom) Validate() goval.Errors {
	errors := goval.Errors{}

	{ // ID
		for k, v := range model.customValidationFunc() {
			errors[k] = append(errors[k], v...)
		}
	}

	return errors
}
